# -------------------------------------------------------------------------- #
# ModelSim clean script for CORDIC project
# -------------------------------------------------------------------------- #

from pathlib import Path
import shutil

MODELSIM_DIR = Path(__file__).resolve().parent

# Directories generated by ModelSim/Python
DIRS_TO_REMOVE = [
    "work",
    "proj",
    "__pycache__",
]

# Files generated by ModelSim
FILE_PATTERNS_TO_REMOVE = [
    "transcript",
    "vsim.wlf",
    "*.wlf",
    "*.mpf",
    "*.mti",
    "*.cr.mti",
    "*.log",
    "*.jou",
    "modelsim.ini",
]


def main():
    print("=== Cleaning ModelSim generated files ===")

    for d in DIRS_TO_REMOVE:
        path = MODELSIM_DIR / d
        if path.exists() and path.is_dir():
            print(f"Removing directory: {path.name}")
            shutil.rmtree(path)

    for pattern in FILE_PATTERNS_TO_REMOVE:
        for path in MODELSIM_DIR.glob(pattern):
            if path.is_file():
                print(f"Removing file: {path.name}")
                path.unlink()

    print("Clean completed.")


if __name__ == "__main__":
    main()